IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo'
      AND TABLE_NAME = 'NhaCungUng'
      AND COLUMN_NAME = 'ChucVu'
      AND DATA_TYPE = 'nvarchar'
      AND CHARACTER_MAXIMUM_LENGTH < 500
)
BEGIN
    ALTER TABLE dbo.NhaCungUng ALTER COLUMN ChucVu nvarchar(500) NULL;
END
