/*
Imports 7 real sample products (3 Công nghệ MISA + 4 Thiết bị) from
D:\2026\CanTho\CSDL Mau\SanphamCNTBMau (customer-provided sample data sheets).
Published directly (StatusId=3). Requires seed-real-suppliers.sql to have run first.
Idempotent — guarded by Name + ProductType.
*/

SET QUOTED_IDENTIFIER ON;
GO

DECLARE @Now DATETIME = GETDATE();

CREATE TABLE #ProdSeed (
    Name NVARCHAR(500), ProductType INT, NCUId INT, XuatXu NVARCHAR(500),
    MoTaNgan NVARCHAR(MAX), MoTa NVARCHAR(MAX), ThongSo NVARCHAR(MAX), UuDiem NVARCHAR(MAX),
    TargetCustomer NVARCHAR(MAX), GiaBanDuKien NVARCHAR(MAX), GiaiThuong NVARCHAR(MAX),
    CategoryId NVARCHAR(500), HoTen NVARCHAR(MAX), DiaChi NVARCHAR(MAX), Phone NVARCHAR(50),
    OwnerEmail NVARCHAR(200), WebUrl NVARCHAR(200), DevelopmentStage NVARCHAR(200),
    ChungNhanISO BIT, ChungNhanKhac BIT, ChungNhanKhacText NVARCHAR(500)
);

INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Bộ giải pháp Quản lý bán hàng cho Hộ, cá nhân kinh doanh MISA eShop',1,8096,N'Trong nước',N'Phần mềm quản lý bán hàng đa kênh chuyên biệt cho hộ kinh doanh, tích hợp bán hàng - hóa đơn điện tử - kê khai thuế - kế toán trên một nền tảng.',N'MISA eShop là giải pháp quản lý bán hàng đa kênh, hợp nhất mọi hoạt động từ online đến offline, đáp ứng hơn 25 ngành nghề (mỹ phẩm, thời trang, tạp hóa, siêu thị mini, nội thất, đồ gia dụng, mẹ và bé...). Mọi nghiệp vụ Bán hàng - Xuất hóa đơn điện tử - Kê khai thuế - Sổ sách kế toán đều thực hiện trên một phần mềm duy nhất, giúp hộ kinh doanh tối ưu quy trình, tiết kiệm thời gian và đảm bảo dữ liệu chính xác, minh bạch.',N'Tính tiền tự động qua quét mã vạch; thanh toán không tiền mặt (chuyển khoản, ví điện tử, QR); in hóa đơn tự động & xuất HDDT máy tính tiền; quản lý tồn kho thời gian thực; quản lý bán hàng đa kênh/đa nền tảng; chatbot AI chăm sóc khách hàng; kết nối đơn vị vận chuyển (J&T, VNPost, GHN, Viettel Post).',N'Quản lý bán hàng trên nhiều nền tảng; tích hợp AI trả lời khách hàng tự động; chốt đơn 24/7; xử lý đơn và giao hàng tiết kiệm chi phí; báo cáo trực quan tùy chỉnh.',N'Doanh nghiệp mọi quy mô (SME đến tập đoàn lớn), tổ chức và hộ, cá nhân kinh doanh.',N'<table border="1"><tr><th>Gói</th><th>Mô tả</th><th>Giá bán dự kiến</th></tr><tr><td>Gói Cơ bản (1 người dùng)</td><td>Phần mềm bán hàng, chữ ký số từ xa, 5000 HĐĐT từ máy tính tiền, 50 lượt xử lý đầu vào/năm</td><td>1.200.000 VNĐ/năm</td></tr><tr><td>Gói Tiêu chuẩn (2 người dùng)</td><td>Phần mềm bán hàng, chữ ký số từ xa, 5000 HĐĐT từ máy tính tiền</td><td>2.400.000 VNĐ/năm</td></tr><tr><td>Gói Chuyên nghiệp (không giới hạn người dùng)</td><td>Phần mềm bán hàng, chữ ký số từ xa, 10000 HĐĐT từ máy tính tiền</td><td>3.600.000 VNĐ/năm</td></tr><tr><td>Gói Nâng cao (chuỗi cửa hàng)</td><td>Phần mềm bán hàng, chữ ký số từ xa, 20000 HĐĐT từ máy tính tiền</td><td>4.800.000 VNĐ/năm/cửa hàng</td></tr></table>',N'Giải thưởng Sao Khuê (2020, 2026 - TOP 10); Giải Đồng Make in Viet Nam 2025; Top 10 Sản phẩm - Dịch vụ Tiên phong 2025.',N'4',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Chữ ký số điện tử MISA eSign',1,8096,N'Trong nước',N'Giải pháp ký số từ xa (Remote Signing) không cần USB Token, ký mọi lúc mọi nơi trên mọi thiết bị.',N'MISA eSign cho phép ký số trực tiếp trên web hoặc thiết bị di động mà không cần USB Token, với quy trình phê duyệt nhiều cấp, xác thực đa lớp (OTP, thiết bị di động, tài khoản người dùng), lưu trữ điện tử tập trung và tích hợp với các hệ thống phần mềm khác (hóa đơn, nhân sự, kế toán). Đáp ứng đầy đủ quy định pháp lý về giao dịch điện tử và chữ ký số tại Việt Nam (Nghị định 130/2018/NĐ-CP).',N'Ký từ xa (Remote Signing) trên smartphone/tablet/laptop; xác thực OTP đa lớp; hỗ trợ ký hàng loạt nhiều tài liệu; tích hợp hệ thống hóa đơn/nhân sự/kế toán.',N'Ký mọi lúc mọi nơi; hình thức ký linh hoạt; lưu trữ thông minh bảo mật; tích hợp hệ thống sẵn sàng mở rộng; đáp ứng đầy đủ tiêu chuẩn pháp lý (xác thực danh tính, toàn vẹn dữ liệu, chống chối bỏ trách nhiệm).',N'Doanh nghiệp mọi quy mô, tổ chức, cơ quan hành chính sự nghiệp, hộ và cá nhân kinh doanh.',N'<table border="1"><tr><th>Gói</th><th>Mô tả</th><th>Giá bán dự kiến</th></tr><tr><td>1 năm</td><td>Gói chữ ký số Hộ, cá nhân kinh doanh</td><td>1.050.000 VNĐ</td></tr><tr><td>2 năm</td><td>Gói chữ ký số Hộ, cá nhân kinh doanh</td><td>1.450.000 VNĐ</td></tr><tr><td>3 năm</td><td>Gói chữ ký số Hộ, cá nhân kinh doanh</td><td>1.750.000 VNĐ</td></tr><tr><td>4 năm</td><td>Gói chữ ký số Hộ, cá nhân kinh doanh</td><td>2.050.000 VNĐ</td></tr><tr><td>5 năm</td><td>Gói chữ ký số Hộ, cá nhân kinh doanh</td><td>1.850.000 VNĐ</td></tr></table>',NULL,N'4',NULL,NULL,NULL,NULL,NULL,NULL,1,1,N'ISO 9001, ISO/IEC 27001, CMMI, CSA STAR; tuân thủ Nghị định 130/2018/NĐ-CP');
INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Hóa đơn điện tử MISA Meinvoice dành cho Hộ, Cá nhân kinh doanh',1,8096,N'Trong nước',N'Nền tảng hóa đơn điện tử trên nền điện toán đám mây cho hộ kinh doanh, kết nối trực tiếp cơ quan thuế, tích hợp chữ ký số MISA eSign.',N'MISA meInvoice là nền tảng hóa đơn điện tử cho phép hộ kinh doanh thực hiện toàn bộ quy trình lập, phát hành, ký số, gửi, tra cứu và lưu trữ hóa đơn trên một hệ thống, đáp ứng Nghị định 70/2025/NĐ-CP và Thông tư 32/2025/TT-BTC. Hỗ trợ hóa đơn điện tử khởi tạo từ máy tính tiền kết nối trực tiếp cơ quan thuế, tích hợp chữ ký số MISA eSign và các nền tảng khác trong hệ sinh thái MISA.',N'Nền tảng Cloud Computing; phát hành HĐĐT trên máy tính/điện thoại/máy tính bảng; kết nối trực tiếp cơ quan thuế; tích hợp chữ ký số MISA eSign.',N'Đáp ứng đầy đủ quy định pháp luật hiện hành; đơn giản hóa quy trình lập-ký-phát hành-gửi hóa đơn; tự động gửi hóa đơn lên cơ quan thuế; tiết kiệm chi phí in ấn/lưu trữ/vận chuyển.',N'Hộ kinh doanh, cá nhân kinh doanh.',N'<p><b>Hóa đơn khởi tạo từ máy tính tiền:</b></p><table border="1"><tr><th>Gói</th><th>Đơn giá</th><th>Thành tiền</th><th>Tương đương</th></tr><tr><td>5.000 HĐ-MTT</td><td>995.000</td><td>995.000</td><td>199đ/hóa đơn</td></tr><tr><td>10.000 HĐ-MTT</td><td>1.400.000</td><td>1.400.000</td><td>140đ/hóa đơn</td></tr><tr><td>20.000 HĐ-MTT</td><td>2.200.000</td><td>2.200.000</td><td>110đ/hóa đơn</td></tr><tr><td>50.000 HĐ-MTT</td><td>4.250.000</td><td>4.250.000</td><td>85đ/hóa đơn</td></tr><tr><td>100.000 HĐ-MTT</td><td>7.000.000</td><td>7.000.000</td><td>70đ/hóa đơn</td></tr></table><p><b>Hóa đơn bán hàng:</b></p><table border="1"><tr><th>Gói</th><th>Đơn giá</th><th>Khuyến mại</th></tr><tr><td>300 hóa đơn</td><td>950.000</td><td>-</td></tr><tr><td>1.000 hóa đơn</td><td>1.550.000</td><td>Tặng 1.000 hoá đơn</td></tr><tr><td>5.000 hóa đơn</td><td>3.650.000</td><td>Tặng 5.000 hoá đơn</td></tr></table>',NULL,N'4',N'Nguyễn Thị Cẩm Tiên (Trưởng phòng PTĐT)',N'VP Misa Cần Thơ, số 17 đường Nguyễn Văn Cừ, P. Cái Khế, TP. Cần Thơ',N'0936347929',N'nctien@cth.misa.com.vn',NULL,NULL,NULL,NULL,NULL);
INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Máy sấy Aobote cho trái cây - rau củ quả',2,7225,N'Trung Quốc',N'Máy sấy bơm nhiệt (Heat Pump) cho trái cây và rau củ quả, tiết kiệm điện, giữ màu và hương vị tự nhiên.',N'Máy sấy Aobote ứng dụng công nghệ bơm nhiệt (Heat Pump), hoạt động theo cơ chế tuần hoàn khép kín: không khí được gia nhiệt, đi qua nguyên liệu để tách ẩm, hơi nước được thu hồi và không khí tiếp tục tái sử dụng. Cấu tạo gồm buồng sấy cách nhiệt, hệ thống bơm nhiệt, quạt tuần hoàn khí nóng, khay sấy inox và bảng điều khiển thông minh (PLC tự động). Ứng dụng rộng rãi trong chế biến nông sản: sấy trái cây lát (xoài, chuối, táo, dứa), trái cây dẻo (mít, thanh long), rau củ (cà rốt, khoai lang, bí đỏ).',N'Công nghệ sấy: Bơm nhiệt (Heat Pump); hệ thống chính: máy nén, dàn bay hơi, dàn ngưng tụ, van tiết lưu; điều khiển PLC tự động; khay sấy inox nhiều tầng; công suất/kích thước thiết kế theo yêu cầu dự án.',N'Tiết kiệm điện năng nhờ công nghệ bơm nhiệt; giữ màu sắc và hương vị tự nhiên; sấy đồng đều; tự động hóa cao, dễ vận hành; phù hợp nhiều quy mô sản xuất từ nhỏ đến công nghiệp.',NULL,NULL,NULL,N'5;12',NULL,NULL,NULL,NULL,NULL,N'Đã thương mại hóa',NULL,NULL,NULL);
INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Máy lọc nước công nghiệp RO KSRO4000/KSRO6000 (Rotek)',2,8887,N'Đài Loan (thương hiệu Rotek)',N'Hệ thống lọc nước thẩm thấu ngược (RO) công nghiệp/thương mại dòng KSRO, lưu lượng 4000-6000 GPD.',N'Hệ thống RO dòng ROTEK KSRO thiết kế theo nguyên tắc "Keep It Simple Stupid", đơn giản để cài đặt, vận hành và bảo dưỡng nhờ thiết kế "Pulse Flush" đáng tin cậy. Tỷ lệ thu hồi cố định 60-65%, sử dụng một màng RO lưu lượng cực lớn tạo ra 4000-6000 GPD (650-1000 LPH) nước thành phẩm.',N'Lưu lượng: 4000-6000 GPD (650-1000 LPH); tỷ lệ thu hồi: 60-65%; màng ROTEK XL-4040; bộ điều khiển RO ROTEK C-5TM (đã cấp bằng sáng chế); có thể nâng cấp bộ điều khiển Wifi RO.',N'Vận hành đơn giản chỉ với một công tắc nguồn; kích thước gọn nhẹ dễ vận chuyển; lưu lượng nước thành phẩm lớn nhất phân khúc; không có van điều chỉnh thông thường tránh thao tác sai.',NULL,NULL,NULL,N'9',N'Hung Chen Yu (Giám đốc)',NULL,N'0902669771',N'cevcsales@cevc.com.vn',NULL,NULL,NULL,NULL,NULL);
INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Đèn LED nhà xưởng China Ecotek (BV120B / BV240)',2,8887,N'Đài Loan',N'Đèn LED công nghiệp 2 dòng: đuôi xoáy 120W (BV120B) và High Bay 240W (BV240), chip gốm COB.',N'Đèn LED đuôi xoáy 120W (BV120B): mạch IC AC chống sét 1KV, chip COB gốm, đuôi tiêu chuẩn E40 thay thế trực tiếp đèn thủy ngân cũ. Đèn LED High Bay 240W (BV240): tấm siêu dẫn gốm COB, thấu kính quang học không tuổi, hệ thống tản nhiệt tích hợp cấp bằng sáng chế, chịu được môi trường bụi/nhiệt độ/độ ẩm cao.',N'<table border="1"><tr><th>Thông số</th><th>BV120B (120W)</th><th>BV240 (240W)</th></tr><tr><td>Nguồn sáng</td><td>Chip gốm COB</td><td>Chip gốm COB</td></tr><tr><td>Góc chiếu sáng</td><td>60°/90°/120°</td><td>25°/60°/90°/120°</td></tr><tr><td>Nhiệt độ màu</td><td>3000K/4500K/5500K</td><td>3000K/4500K/5500K</td></tr><tr><td>Độ sáng</td><td>≥120Lm/W</td><td>≥120Lm/W</td></tr><tr><td>Chỉ số tạo màu</td><td>80Ra</td><td>80Ra</td></tr><tr><td>Nguồn</td><td>IC Driver AC 220V</td><td>MEAN WELL AC 220V/90-305V/180-520V</td></tr><tr><td>Môi trường sử dụng</td><td>-25°C~50°C</td><td>-25°C~50°C</td></tr><tr><td>Cấp bảo vệ</td><td>-</td><td>IP68 (nguồn IP65)</td></tr><tr><td>Đuôi nối</td><td>E40</td><td>-</td></tr><tr><td>Trọng lượng</td><td>1.2Kg</td><td>4.3Kg</td></tr></table>',N'Chống sét 1KV; chip COB nguồn sáng tập trung, hệ số điện trở nhiệt thấp; tản nhiệt hợp nhất; khối lượng nhẹ; BV240 đạt chuẩn IP68 chịu môi trường khắc nghiệt.',NULL,NULL,NULL,N'4',N'Hung Chen Yu (Giám đốc)',NULL,N'0902669771',N'cevcsales@cevc.com.vn',NULL,NULL,NULL,NULL,NULL);
INSERT INTO #ProdSeed (Name,ProductType,NCUId,XuatXu,MoTaNgan,MoTa,ThongSo,UuDiem,TargetCustomer,GiaBanDuKien,GiaiThuong,CategoryId,HoTen,DiaChi,Phone,OwnerEmail,WebUrl,DevelopmentStage,ChungNhanISO,ChungNhanKhac,ChungNhanKhacText) VALUES (N'Lò hơi tầng sôi',2,8892,N'Chế tạo và lắp đặt bởi Công ty TNHH Phúc Trường Hải',N'Lò hơi tầng sôi (Fluidized Bed Boiler) công suất 5-50 Tấn/giờ, đốt đa nhiên liệu biomass, hiệu suất đến 88%.',N'Hệ thống hoạt động dựa trên nguyên lý đốt cháy nhiên liệu trong lớp hạt trơ (cát thạch anh) giữ ở trạng thái lơ lửng nhờ dòng không khí nén áp lực cao (trạng thái tầng sôi). Nhiên liệu cấp vào buồng đốt gặp nhiệt độ cao của lớp cát sôi sẽ bốc cháy tức thời, truyền nhiệt đến các vách ống nước để sinh hơi. Khói thải đi qua hệ thống thu hồi nhiệt (bộ tiết kiệm nước, bộ sấy gió) và hệ thống xử lý đa tầng (cyclone chùm, lọc bụi túi vải/tháp dập bụi) trước khi thoát ra ống khói.',N'Loại lò hơi: Lò hơi tầng sôi (Fluidized Bed Boiler); công suất sinh hơi: 5-50 Tấn/giờ; áp suất thiết kế: dưới 50 bar; hiệu suất đầu lò: 85-88% (khi tích hợp bộ tiết kiệm nhiệt Eco và bộ sấy không khí); nhiên liệu: đa nhiên liệu (biomass dạng dăm quế, củi trấu, viên nén mùn cưa, than cám).',N'Đốt nhiên liệu rẻ tiền, độ ẩm cao giúp tối ưu chi phí sinh hơi 30-40% so với lò dầu/gas; cháy ở nhiệt độ thấp (800-900°C) giảm khí độc NOx; điều khiển tự động hoàn toàn (PLC-SCADA), vận hành an toàn 24/7.',NULL,NULL,NULL,N'9;12;5',NULL,N'KCN Thạnh Phú, phường Tân Triều, TP. Đồng Nai, Việt Nam',N'0906766812',N'linh.nguyen@phuctruonghai.vn',N'https://phuctruonghai.vn/',N'Đã thương mại hóa',NULL,NULL,NULL);

DECLARE @BaseId INT = (SELECT ISNULL(MAX(ID),0)+1 FROM SanPhamCNTB);

INSERT INTO SanPhamCNTB
    (Name, ProductType, NCUId, XuatXu, MoTaNgan, MoTa, ThongSo, UuDiem, TargetCustomer,
     GiaBanDuKien, GiaiThuong, CategoryId, HoTen, DiaChi, Phone, OwnerEmail,
     WebUrl, DevelopmentStage, ChungNhanISO, ChungNhanKhac, ChungNhanKhacText,
     Code, StatusId, LanguageId, SiteId, Created, Modified, Creator, OwnerType)
SELECT
    s.Name, s.ProductType, s.NCUId, s.XuatXu, s.MoTaNgan, s.MoTa, s.ThongSo, s.UuDiem, s.TargetCustomer,
    s.GiaBanDuKien, s.GiaiThuong, s.CategoryId, s.HoTen, s.DiaChi, s.Phone, s.OwnerEmail,
    s.WebUrl, s.DevelopmentStage, s.ChungNhanISO, s.ChungNhanKhac, s.ChungNhanKhacText,
    CASE WHEN s.ProductType=1 THEN 'CN-' ELSE 'TB-' END + RIGHT('00000' + CAST(@BaseId + ROW_NUMBER() OVER (ORDER BY s.Name) - 1 AS VARCHAR(5)), 5),
    3, 1, 1, @Now, @Now, 'sample-import', 1
FROM #ProdSeed s
WHERE NOT EXISTS (SELECT 1 FROM SanPhamCNTB p WHERE p.Name = s.Name AND p.ProductType = s.ProductType);

DROP TABLE #ProdSeed;
GO