-- ============================================================
-- NhaCungUng: Add new columns per PHIẾU THÔNG TIN mẫu
-- Run on TechExchangeNew database
-- ============================================================

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaCungUng' AND COLUMN_NAME='TenVietTat')
    ALTER TABLE dbo.NhaCungUng ADD TenVietTat NVARCHAR(300) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaCungUng' AND COLUMN_NAME='LoaiHinhToChuc')
    ALTER TABLE dbo.NhaCungUng ADD LoaiHinhToChuc NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaCungUng' AND COLUMN_NAME='MaSoThue')
    ALTER TABLE dbo.NhaCungUng ADD MaSoThue NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaCungUng' AND COLUMN_NAME='Logo')
    ALTER TABLE dbo.NhaCungUng ADD Logo NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaCungUng' AND COLUMN_NAME='VideoUrl')
    ALTER TABLE dbo.NhaCungUng ADD VideoUrl NVARCHAR(500) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaCungUng' AND COLUMN_NAME='ChungNhan')
    ALTER TABLE dbo.NhaCungUng ADD ChungNhan NVARCHAR(MAX) NULL;

PRINT 'NhaCungUng columns added successfully.';
