-- ============================================================
-- NhaTuVan: Add new columns per PHIẾU THÔNG TIN mẫu
-- Run on TechExchangeNew database
-- ============================================================

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='MaDinhDanh')
    ALTER TABLE dbo.NhaTuVan ADD MaDinhDanh NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='TongTrichDan')
    ALTER TABLE dbo.NhaTuVan ADD TongTrichDan INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='HIndex')
    ALTER TABLE dbo.NhaTuVan ADD HIndex INT NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='QuaTrinhDaoTao')
    ALTER TABLE dbo.NhaTuVan ADD QuaTrinhDaoTao NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='QuaTrinhCongTac')
    ALTER TABLE dbo.NhaTuVan ADD QuaTrinhCongTac NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='CongBoKhoaHoc')
    ALTER TABLE dbo.NhaTuVan ADD CongBoKhoaHoc NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='SangChe')
    ALTER TABLE dbo.NhaTuVan ADD SangChe NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='DuAnNghienCuu')
    ALTER TABLE dbo.NhaTuVan ADD DuAnNghienCuu NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='KinhNghiem')
    ALTER TABLE dbo.NhaTuVan ADD KinhNghiem NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='HoSoDinhKem')
    ALTER TABLE dbo.NhaTuVan ADD HoSoDinhKem NVARCHAR(MAX) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='NhaTuVan' AND COLUMN_NAME='HiepHoiKhoaHoc')
    ALTER TABLE dbo.NhaTuVan ADD HiepHoiKhoaHoc NVARCHAR(500) NULL;

PRINT 'NhaTuVan columns added successfully.';
